name: CI

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Your existing steps which check out the repo, start-ci-run, install
      # dependencies, etc.
      # These are just illustrative examples...
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npx nx-cloud start-ci-run
      - run: npm ci
      - run: npx nx affected -t lint test build

      # NEW: Add this step at the end of your job
      - run: npx nx fix-ci
        if: always() # IMPORTANT: Always run
